server:
  port: 8001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mastkeyxgod/ProxyRestMicroservice-config.git
  security:
    user:
      password: admin